apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaelephant-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaelephant
  template:
    metadata:
      labels:
        app: javaelephant
    spec:
      containers:
      - name: javaelephant
        image: helga09/elephant:0.5.4
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: javaelephant-service
  namespace: default
   annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: dms
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7000
  selector:
    app: javaelephant
