apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaelephant-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaelephant
  template:
    metadata:
      labels:
        app: javaelephant
    spec:
      containers:
      - name: javaelephant
        image: helga09/elephant:0.3.195
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: javaelephant-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7000
  selector:
    app: javaelephant
