---
apiVersion: v1
data:
  APP.PORT: "7000"
  APP.URL: 'http://127.0.0.1:7000'
  DB.HOST: 127.0.0.1
  DB.LOCAL_PATH: home\tmp\
  DB.NAME: elephant
  DB.OS_USER: WINDOWS
  DB.PASSWORD: test
  DB.PORT: "5432"
  DB.URL: 127.0.0.1
  DB.USERNAME: postgres
  DEFAULT_LANG: EN
  EMAIL.FROM: service-mail@gmail.com
  EMAIL.HOST: smtp.gmail.com
  EMAIL.PASSWORD: my-secret-password
  EMAIL.PORT: "465"
  EMAIL.SSL: "true"
  EMAIL.USER: service-mail@gmail.com
  ENV: PRODUCTION
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaelephant-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaelephant
  template:
    metadata:
      labels:
        app: javaelephant
    spec:
      containers:
      - name: javaelephant
        image: helga09/javaelephant:0.0.2
        ports:
        - containerPort: 7000
        envFrom:
        - configMapRef:
            name: env-config
---
apiVersion: v1
kind: Service
metadata:
  name: javaelephant-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7000
  selector:
    app: javaelephant
